---
- name: build container image for website
  shell: "cd /project/website && docker build -t website:latest ."
  register: build_image_output

- name: Show output of website
  debug:
    msg: "Container Output: {{build_image_output.stdout}}"
