---
- hosts: slave
  become: true
  become_user: edureka
  remote_user: edureka
  sudo: true
  sudo_user: edureka
  roles:
  - git
  - chromium
  - chromedriver
  - docker
  vars:
    ansible_become_password: edureka
