---
- name: download chromedriver
  shell: "wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip"
  register: download_chromedriver

- name: Show output of download
  debug:
    msg: "Container Output: {{download_chromedriver.stdout}}"

- name: unzip chromedriver
  shell: "unzip chromedriver_linux64.zip"
  register: unzip_chromedriver

- name: Show output of download
  debug:
    msg: "Container Output: {{unzip_chromedriver.stdout}}"

- name: permissions chromedriver
  shell: "mv chromedriver /usr/bin/chromedriver && chown root:root /usr/bin/chromedriver && chmod +x /usr/bin/chromedriver"
